### ISSUE TITLE
Stolen idea

### ISSUE THREAD

**Issue by Georgesab** [MagicJinn/MrBeastify-Youtube#10]
Blatantly stole this idea from Unnecessary inventions, at least give him credit!

You even stole the name!

https://www.mrbeastify.com

https://www.youtube.com/watch?v=UVG2UPZRA20

**Comment by DaryeDev** [comment]
☝🤓

**Comment by MagicJinn** [comment]
While I personally would phrase it as inspiration, you are absolutely right that I did not properly credit Unnecessary Inventions where applicable. I'll edit the readme to include proper credits, and update the add-on pages as soon as possible, but I ask your patience on the latter, since this requires a manual review which can take hours to days. Thank you for your report!

**Comment by Georgesab** [comment]
Thank you!
