### ISSUE TITLE
The question about extension upload

### ISSUE THREAD

**Issue by JoNoteJoMaMa** [MagicJinn/MrBeastify-Youtube#16]
Hello, First of all, I've to say that your project is very significant. <br/>I've forked your project and changed MrBeast images to be someone popular in my country. The question is, can I upload my version of this project to Google extension with all of your credit for this project?

**Comment by MagicJinn** [comment]
Hey there! I'll guide you through the process as far as I remember it. Also, if you haven't done so already, make sure that your fork is up to date with the main branch. We fixed a bunch of bugs and I created a system that indexes the images folder instead of requiring a hardcoded list in manifest.json and mrbeasify.js.

1. Prepare the manifests: Be sure to rename the extension and give it a proper version number in the manifest.json and manifest v3.json files.
2. Pack extensions: Create a .zip containing icons, images, manifest.json and mrbeasify.js. This is your Firefox add-on. Then create a .zip with the same contents, but instead of using the original manifest.json, rename the V3 version to manifest.js and pack that instead of the original. This is your Chrome extension.
3. Upload your extension to the Firefox store: Go to the [Firefox developer hub](http://addons.mozilla.org/developers/addons), click submit new add-on, then upload the .zip meant for Firefox. Make sure to fill out any information that is relevant, like required permissions etc. Publish your extension. This process can take hours to a day.
4. Upload your extension to the Chrome store: Go to the [Chrome add-on store](http://chrome.google.com/webstore), click the gear in the top right, click Developer Dashboard. From there I don't know the exact instructions. Beware that Google requires a 5 dollar payment from a credit card in order to upload extensions. Upload the .zip meant for Chrome, make sure to fill out any information that is relevant, like required permissions etc. Publish your extension. This process can take several days.

This should be all if I remember correctly. Uploading to the Edge store is an option, but their review process takes up to a week, and Edge users can download from the Chrome store anyway. Let me know if you have any other questions! I'm here to help!

And as for credit, you can link my Firefox extension on the Firefox add-on page, and my Chrome extension on the Chrome add-on page, or you could link my Github on both.

**Comment by JoNoteJoMaMa** [comment]
Wow, you're such a kind person. Thank you so much!
