### ISSUE TITLE
Impact Hero in Chrome bundle (not in repository)

### ISSUE THREAD

**Issue by nyakase** [MagicJinn/MrBeastify-Youtube#56]
When I woke up this morning I found that my beloved MrBeastify extension [suddenly wanted optional access to all tabs](https://github.com/MagicJinn/MrBeastify-Youtube/assets/46850780/b6e4b601-1c58-465b-bd93-8a1be0a81fd4).

This comes from a company called "Impact Hero" whose code was added to the Chrome extension. They track visits to various supported sites and send data about your visit to their servers for the purpose of carbon offsets.

![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/46850780/d4009430-e446-4c28-82fa-bfd7f95d4b5d)

----

This implementation seems to violate the [Chrome Web Store Limited Use](https://developer.chrome.com/docs/webstore/program-policies/limited-use) policy the extension is currently under.

> You must limit your use of the data to the practices you disclosed.

The disclosure on the Web Store says that data is not sold or transferred. Visit data is transferred to Impact Hero.

> Collection and use of web browsing activity is prohibited, except to the extent required for a user-facing feature described prominently in the Product's Chrome Web Store page and in the Product's user interface.

This feature is not described at all on the Web Store page. It is not prominently disclosed in the user interface - while the extension does *ask* for the permission the interface does not explain what the permission does, only saying that "the new tab that is opened is used to calculate carbon offsets".

----

I'm uninstalling the extension for now as I don't think I can trust it with this sudden addition that was excluded from the GitHub repository. I'd like to hear more about why this was added and why the feature isn't disclosed more clearly.

**Comment by MagicJinn** [comment]
Thanks for reaching out. I am currently not in a position to give a full response, but rest assured I take this issue very seriously. I will get back to you with a full response on this in a few hours.

**Comment by MagicJinn** [comment]
Update: version has been rolled back to previous version until this is resolved. (on Chrome)

**Comment by MagicJinn** [comment]
The updated version of the extension has been submitted to the Chrome Web Store with several new changes. Firstly, I've revised the wording in the pop-up, which previously caused confusion, across all languages the extension supports. Additionally, I've provided a proper description on the Chrome Web Store page. It was my oversight, and I take full responsibility for not disclosing all necessary information initially. The pop-up wording has also been adjusted to be less confusing.

> that was excluded from the GitHub repository.

The Impact Hero Code isn't visible in the GitHub repository because, by contract, I am not allowed to redistribute their SDK. However, you can access the code directly on the Chrome Store by downloading the extension and inspecting it. Nothing is obfuscated; everything is plain and readable.
Another reason I didn't upload it to GitHub is to prevent the code from spreading to other forks of my project unintentionally. This extension-specific code should remain within its intended scope.

Then, on the question why I reversed the changes after I got "caught".
I intended to include these updates in a subsequent release this week, but after you raised these issues, I realized it would not be fair for the people who currently have the extension installed to keep the update online. I reverted to the latest version without the SDK. This allows users who had accepted the permissions to reassess with complete information.

Lastly, I want to clarify that this feature is entirely opt-in. You are not obligated to accept the permissions; clicking "deny" will still allow the extension to function normally. This was of course not clear before, due to the misleading wording.
