### ISSUE TITLE
MrBeast himself is MrBeastified

### ISSUE THREAD

**Issue by mayhair** [MagicJinn/MrBeastify-Youtube#6]
will you fix this, or will you make it a "feature, not a bug" because it's funny?

![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/21954283/4f09d9c9-d8dc-497e-b401-46018c310101)

**Comment by MagicJinn** [comment]
Nope, we won't fix that because

1. Creating a filter to filter out MrBeasts videos is something above the scope of my coding skills
2. That's funny as hell

**Comment by krystian3w** [comment]
Maybe CSS4 will be enough to found link in big rectangle:
```css
/* Pseudo CSS */
rectangle:has(a[href*="@MrBeast]) thumbnail { /* ... */ }
```

But harder will be detect opened channel or CO video without credits in title.

I have no idea if there is any nice function in Vanilla JS to use a replacement for `has` to provide support for the oldest supported Chromiums below 105 release and all Firefox due to plans to implement this in CSS 116 or later without messing with `about :config`.
